name:        Grendel
version:     0.1.0

synopsis:    'A comic book viewer'
description: 'A comic book viewer'
category:    Web
license:     MIT

homepage:    https://github.com/sshine/Grendel
author:      Simon Shine
maintainer:  shreddedglory@gmail.com
copyright:   2020 Simon Shine

default-extensions:
  - OverloadedStrings

dependencies:
  - base
  - aeson
  - bytestring
  - containers
  - directory
  - filepath
  - gogol
  - gogol-core
  - gogol-drive
  - http-client
  - microlens
# - optparse-generic
  - resourcet
  - servant
  - servant-client
  - JuicyPixels
  - servant-JuicyPixels
  - servant-server
  - text
  - wai
  - warp

library:
  source-dirs: src

executable:
  main: Main.hs
  source-dirs: app
  dependencies:
    - Grendel

tests:
  test:
    main: test.hs
    source-dirs: test
    dependencies:
      - Grendel
      - tasty
      - tasty-discover
      - tasty-hspec
      - tasty-hedgehog
      - hedgehog
      - hspec
      - hspec-wai
