resolver: lts-16.20
packages:
  - .
extra-deps:
  - git: https://github.com/haskell-servant/servant.git
    commit: c1105899f47d5537c1bdc8c86bee3523bdf05282
    subdirs:
      - servant
      - servant-client
      - servant-client-core
      - servant-server
