name: Haskell CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc:
          - "8.8.4"
          - "8.10.2"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-haskell@v1.1.3
        with:
          ghc-version: ${{ matrix.ghc }}
          enable-stack: true
      - uses: actions/cache@v2
        with:
          path: |
            ~/.local/bin
            ~/.stack
            .stack-work
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('stack.yaml.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-
      - run: stack install tasty-discover
      - run: stack build
      - run: stack test
#     - run: stack haddock
#     - run: stack sdist
